import type { Food } from "./types";

/**
 * Static demo dataset mirroring supabase/seed.sql. Used as a fallback so the
 * site shows realistic content when Supabase is not configured AND demo mode
 * is explicitly enabled via NEXT_PUBLIC_DEMO_MODE=1 (e.g. previews / docs
 * screenshots). It never overrides a real Supabase connection.
 */
export const DEMO_FOODS: Food[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    name_ko: "치즈 랍스터",
    name_en: "Cheese Lobster",
    name_ja: "チーズロブスター",
    name_es: "Langosta con Queso",
    description:
      "반으로 가른 랍스터 위에 모짜렐라 치즈를 듬뿍 올려 토치로 구운 명동 명물.",
    translations: {
      en: "Half a lobster loaded with mozzarella and torched to bubbly perfection — a Myeongdong icon.",
      ja: "半分に割ったロブスターにモッツァレラをたっぷりのせ、バーナーで炙った明洞名物。",
      es: "Media langosta cubierta de mozzarella y gratinada al soplete, un ícono de Myeongdong.",
    },
    category: "해산물",
    lat: 37.5642,
    lng: 126.9848,
    address: "서울 중구 명동길 12",
    youtube_shorts_url: "https://www.youtube.com/shorts/Lr7cH2zX5pQ",
    thumbnail_url: "/demo/lobster.svg",
    hashtags: ["치즈랍스터", "명동명물", "비주얼", "해산물"],
    view_count: 3015,
    is_trending: true,
    price_range: "₩15,000~20,000",
    created_at: "2024-05-20T09:00:00.000Z",
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    name_ko: "호떡",
    name_en: "Hotteok",
    name_ja: "ホットク",
    name_es: "Hotteok",
    description:
      "바삭한 겉면 속에 흑설탕과 견과류가 가득. 겨울 명동을 대표하는 따끈한 간식입니다.",
    translations: {
      en: "Crispy pancake filled with molten brown sugar and nuts — the warm winter treat of Myeongdong.",
      ja: "カリッとした生地に黒砂糖とナッツがたっぷり。冬の明洞を代表する温かいおやつ。",
      es: "Panqueque crujiente relleno de azúcar moreno fundido y nueces, el dulce caliente del invierno en Myeongdong.",
    },
    category: "간식",
    lat: 37.5639,
    lng: 126.9829,
    address: "서울 중구 명동8길 21",
    youtube_shorts_url: "https://www.youtube.com/shorts/3sJf9bq5mWk",
    thumbnail_url: "/demo/hotteok.svg",
    hashtags: ["겨울간식", "호떡", "달달", "명동"],
    view_count: 2410,
    is_trending: true,
    price_range: "₩2,000~3,000",
    created_at: "2024-05-18T09:00:00.000Z",
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    name_ko: "떡볶이",
    name_en: "Tteokbokki",
    name_ja: "トッポッキ",
    name_es: "Tteokbokki",
    description:
      "쫄깃한 가래떡과 매콤달콤한 고추장 양념이 어우러진 명동 대표 길거리 음식. 어묵, 삶은 계란과 함께 즐겨보세요.",
    translations: {
      en: "Chewy rice cakes in a sweet-and-spicy gochujang sauce — Myeongdong's signature street snack. Great with fish cake and boiled eggs.",
      ja: "もちもちの餅と甘辛いコチュジャンソースが絡む明洞名物。おでんやゆで卵と一緒にどうぞ。",
      es: "Pasteles de arroz masticables en salsa de gochujang agridulce, el clásico de Myeongdong. Rico con pastel de pescado y huevo cocido.",
    },
    category: "분식",
    lat: 37.5636,
    lng: 126.9857,
    address: "서울 중구 명동길 14",
    youtube_shorts_url: "https://www.youtube.com/shorts/ZpM0pZ8wMqA",
    thumbnail_url: "/demo/tteokbokki.svg",
    hashtags: ["매콤", "분식", "명동맛집", "떡볶이"],
    view_count: 1820,
    is_trending: true,
    price_range: "₩3,000~5,000",
    created_at: "2024-05-15T09:00:00.000Z",
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    name_ko: "회오리 감자",
    name_en: "Tornado Potato",
    name_ja: "トルネードポテト",
    name_es: "Patata Tornado",
    description:
      "감자를 회오리 모양으로 깎아 튀긴 바삭한 간식. 다양한 시즈닝을 골라보세요.",
    translations: {
      en: "A whole potato spiral-cut and deep-fried until crispy — pick your favorite seasoning.",
      ja: "じゃがいもを竜巻状にカットして揚げたサクサクおやつ。好きな味付けを選んで。",
      es: "Una patata cortada en espiral y frita hasta quedar crujiente; elige tu condimento favorito.",
    },
    category: "간식",
    lat: 37.5631,
    lng: 126.9835,
    address: "서울 중구 명동길 18",
    youtube_shorts_url: "https://www.youtube.com/shorts/Tq8wZ1nP4xY",
    thumbnail_url: "/demo/potato.svg",
    hashtags: ["회오리감자", "바삭", "인스타", "간식"],
    view_count: 1675,
    is_trending: true,
    price_range: "₩4,000~5,000",
    created_at: "2024-05-12T09:00:00.000Z",
  },
  {
    id: "55555555-5555-4555-8555-555555555555",
    name_ko: "왕만두",
    name_en: "Wang Mandu",
    name_ja: "왕만두",
    name_es: "Wang Mandu",
    description:
      "김이 모락모락 나는 손만두. 고기만두와 김치만두 모두 인기 만점입니다.",
    translations: {
      en: "Steaming hand-made dumplings — both the pork and kimchi fillings are crowd favorites.",
      ja: "湯気立つ手作り餃子。肉まんもキムチまんも大人気。",
      es: "Empanadillas artesanales humeantes; tanto las de cerdo como las de kimchi triunfan.",
    },
    category: "분식",
    lat: 37.5625,
    lng: 126.9841,
    address: "서울 중구 명동2길 32",
    youtube_shorts_url: "https://www.youtube.com/shorts/k2Lp9sQ7wDc",
    thumbnail_url: "/demo/mandu.svg",
    hashtags: ["만두", "왕만두", "김치만두", "든든"],
    view_count: 1340,
    is_trending: false,
    price_range: "₩4,000~6,000",
    created_at: "2024-05-10T09:00:00.000Z",
  },
  {
    id: "66666666-6666-4666-8666-666666666666",
    name_ko: "닭꼬치",
    name_en: "Dak-kkochi",
    name_ja: "タッコチ",
    name_es: "Brocheta de Pollo",
    description:
      "숯불에 구워 매콤달콤 양념을 바른 닭꼬치. 한 손에 들고 명동 거리를 걸어보세요.",
    translations: {
      en: "Charcoal-grilled chicken skewers glazed in sweet-spicy sauce — eat one on the go.",
      ja: "炭火で焼き、甘辛いタレを塗ったチキン串。片手に持って明洞を歩こう。",
      es: "Brochetas de pollo a la brasa con salsa agridulce; cómelas mientras paseas.",
    },
    category: "꼬치",
    lat: 37.5609,
    lng: 126.9863,
    address: "서울 중구 명동길 31",
    youtube_shorts_url: "https://www.youtube.com/shorts/Bn4kL0qR9sM",
    thumbnail_url: "/demo/dakkkochi.svg",
    hashtags: ["닭꼬치", "숯불", "매콤", "꼬치"],
    view_count: 1120,
    is_trending: false,
    price_range: "₩3,000~4,000",
    created_at: "2024-05-08T09:00:00.000Z",
  },
  {
    id: "77777777-7777-4777-8777-777777777777",
    name_ko: "계란빵",
    name_en: "Gyeranppang",
    name_ja: "ケランパン",
    name_es: "Gyeranppang",
    description:
      "폭신한 빵 위에 통계란을 얹어 구운 든든한 길거리 간식. 고소하고 달콤합니다.",
    translations: {
      en: "Fluffy bread baked with a whole egg on top — a hearty, savory-sweet street snack.",
      ja: "ふわふわのパンに丸ごと卵をのせて焼いた、香ばしくて満足感のある屋台おやつ。",
      es: "Pan esponjoso horneado con un huevo entero encima, un bocado callejero sabroso y saciante.",
    },
    category: "간식",
    lat: 37.5612,
    lng: 126.9859,
    address: "서울 중구 명동길 27",
    youtube_shorts_url: "https://www.youtube.com/shorts/9aQp1mD2kL0",
    thumbnail_url: "/demo/gyeranppang.svg",
    hashtags: ["계란빵", "아침대용", "고소함", "간식"],
    view_count: 980,
    is_trending: false,
    price_range: "₩2,000~3,000",
    created_at: "2024-05-05T09:00:00.000Z",
  },
  {
    id: "88888888-8888-4888-8888-888888888888",
    name_ko: "붕어빵",
    name_en: "Bungeoppang",
    name_ja: "たい焼き",
    name_es: "Bungeoppang",
    description: "팥이 가득 들어간 따끈한 붕어빵. 슈크림 버전도 함께 판매합니다.",
    translations: {
      en: "Warm fish-shaped pastry packed with sweet red bean — custard version also available.",
      ja: "あんこたっぷりの温かいたい焼き。カスタード味も販売中。",
      es: "Bollo caliente en forma de pez relleno de pasta de judía dulce; también con crema.",
    },
    category: "간식",
    lat: 37.562,
    lng: 126.983,
    address: "서울 중구 명동7길 8",
    youtube_shorts_url: "https://www.youtube.com/shorts/Pf3nQ8wK1aB",
    thumbnail_url: "/demo/bungeoppang.svg",
    hashtags: ["붕어빵", "팥", "겨울간식", "추억"],
    view_count: 760,
    is_trending: false,
    price_range: "₩2,000~3,000",
    created_at: "2024-05-02T09:00:00.000Z",
  },
];

export const isDemoMode = () => process.env.NEXT_PUBLIC_DEMO_MODE === "1";
